# Site settings
title: Dinh dưỡng Hoàn Mỹ
email: luncheryvn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.dinhduonghoanmy.com" # the base hostname & protocol for your site
twitter_username: jekyllrb

# Build settings
markdown: kramdown
paginate: 5

authors:
  anhnguyen:
    name: Nguyen Quoc Anh
    display_name: Anh DH Nguyen
    image_url: "/assets/anhnguyen.jpg"
  nxqd:
    name: Nguyen Xuan Quang Dung
    display_name: Dung Nguyen
    image_url: "/assets/nxqd.jpg"

# Social
social_sharing:
  provider: enabled
  facebook:
    appid: 591309840991390
    layout: button_count
    faces: false
    width: 90
